# LINEAR REGRESSION ONE VARIABLE

In [46]:
import numpy as np
import pandas as pd
import math
import matplotlib
import IPython.display

## Parameters

In [47]:
df= pd.read_csv('D:\Documentos\Machine Learning\Linear regression coursera\Gold Price Prediction.csv')
print(df.head(10))

      Date  Price 2 Days Prior  Price 1 Day Prior  Price Today  \
0   8/7/24             2405.87            2384.90      2385.83   
1   8/6/24             2442.74            2405.87      2384.90   
2   8/5/24             2447.17            2442.74      2405.87   
3   8/2/24             2447.23            2447.17      2442.74   
4   8/1/24             2411.09            2447.23      2447.17   
5  7/31/24             2382.47            2411.09      2447.23   
6  7/30/24             2387.11            2382.47      2411.09   
7  7/29/24             2365.37            2387.11      2382.47   
8  7/26/24             2400.12            2365.37      2387.11   
9  7/25/24             2409.86            2400.12      2365.37   

   Price Tomorrow  Price Change Tomorrow  Price Change Ten  Std Dev 10  \
0             NaN                    NaN               NaN   30.155078   
1         2385.83                   0.93               NaN   29.423936   
2         2384.90                 -20.97           

In [83]:
x=df['Price Today'].to_numpy()
#x = np.arange(1, 677)
y=df['Price Tomorrow'].to_numpy()
display (x, y)

array([2385.83, 2384.9 , 2405.87, 2442.74, 2447.17, 2447.23, 2411.09,
       2382.47, 2387.11, 2365.37, 2400.12, 2409.86, 2397.05, 2400.95,
       2442.71, 2462.44, 2469.65, 2423.87, 2411.71, 2416.76, 2373.98,
       2366.46, 2363.1 , 2392.24, 2357.89, 2360.4 , 2331.66, 2333.56,
       2326.73, 2299.26, 2321.37, 2332.14, 2320.79, 2361.46, 2330.63,
       2329.73, 2321.51, 2333.02, 2303.26, 2322.23, 2316.43, 2311.13,
       2293.85, 2375.74, 2354.75, 2327.09, 2348.47, 2327.36, 2345.01,
       2338.59, 2360.67, 2353.24, 2334.2 , 2334.61, 2383.23, 2422.84,
       2427.81, 2413.94, 2380.32, 2386.97, 2358.73, 2339.65, 2360.48,
       2346.1 , 2310.43, 2316.67, 2327.59, 2302.57, 2304.87, 2322.67,
       2296.55, 2334.46, 2337.94, 2330.8 , 2316.27, 2323.65, 2334.01,
       2390.86, 2380.14, 2367.91, 2382.59, 2381.97, 2344.53, 2376.89,
       2335.6 , 2354.86, 2338.94, 2329.93, 2289.02, 2297.61, 2279.8 ,
       2249.08, 2232.75, 2190.72, 2179.72, 2173.1 , 2165.64, 2181.81,
       2204.04, 2157

array([    nan, 2385.83, 2384.9 , 2405.87, 2442.74, 2447.17, 2447.23,
       2411.09, 2382.47, 2387.11, 2365.37, 2400.12, 2409.86, 2397.05,
       2400.95, 2442.71, 2462.44, 2469.65, 2423.87, 2411.71, 2416.76,
       2373.98, 2366.46, 2363.1 , 2392.24, 2357.89, 2360.4 , 2331.66,
       2333.56, 2326.73, 2299.26, 2321.37, 2332.14, 2320.79, 2361.46,
       2330.63, 2329.73, 2321.51, 2333.02, 2303.26, 2322.23, 2316.43,
       2311.13, 2293.85, 2375.74, 2354.75, 2327.09, 2348.47, 2327.36,
       2345.01, 2338.59, 2360.67, 2353.24, 2334.2 , 2334.61, 2383.23,
       2422.84, 2427.81, 2413.94, 2380.32, 2386.97, 2358.73, 2339.65,
       2360.48, 2346.1 , 2310.43, 2316.67, 2327.59, 2302.57, 2304.87,
       2322.67, 2296.55, 2334.46, 2337.94, 2330.8 , 2316.27, 2323.65,
       2334.01, 2390.86, 2380.14, 2367.91, 2382.59, 2381.97, 2344.53,
       2376.89, 2335.6 , 2354.86, 2338.94, 2329.93, 2289.02, 2297.61,
       2279.8 , 2249.08, 2232.75, 2190.72, 2179.72, 2173.1 , 2165.64,
       2181.81, 2204

In [84]:
x = np.nan_to_num(x, nan=2000)
y= np.nan_to_num(y, nan=2000)
display(x,y)

array([2385.83, 2384.9 , 2405.87, 2442.74, 2447.17, 2447.23, 2411.09,
       2382.47, 2387.11, 2365.37, 2400.12, 2409.86, 2397.05, 2400.95,
       2442.71, 2462.44, 2469.65, 2423.87, 2411.71, 2416.76, 2373.98,
       2366.46, 2363.1 , 2392.24, 2357.89, 2360.4 , 2331.66, 2333.56,
       2326.73, 2299.26, 2321.37, 2332.14, 2320.79, 2361.46, 2330.63,
       2329.73, 2321.51, 2333.02, 2303.26, 2322.23, 2316.43, 2311.13,
       2293.85, 2375.74, 2354.75, 2327.09, 2348.47, 2327.36, 2345.01,
       2338.59, 2360.67, 2353.24, 2334.2 , 2334.61, 2383.23, 2422.84,
       2427.81, 2413.94, 2380.32, 2386.97, 2358.73, 2339.65, 2360.48,
       2346.1 , 2310.43, 2316.67, 2327.59, 2302.57, 2304.87, 2322.67,
       2296.55, 2334.46, 2337.94, 2330.8 , 2316.27, 2323.65, 2334.01,
       2390.86, 2380.14, 2367.91, 2382.59, 2381.97, 2344.53, 2376.89,
       2335.6 , 2354.86, 2338.94, 2329.93, 2289.02, 2297.61, 2279.8 ,
       2249.08, 2232.75, 2190.72, 2179.72, 2173.1 , 2165.64, 2181.81,
       2204.04, 2157

array([2000.  , 2385.83, 2384.9 , 2405.87, 2442.74, 2447.17, 2447.23,
       2411.09, 2382.47, 2387.11, 2365.37, 2400.12, 2409.86, 2397.05,
       2400.95, 2442.71, 2462.44, 2469.65, 2423.87, 2411.71, 2416.76,
       2373.98, 2366.46, 2363.1 , 2392.24, 2357.89, 2360.4 , 2331.66,
       2333.56, 2326.73, 2299.26, 2321.37, 2332.14, 2320.79, 2361.46,
       2330.63, 2329.73, 2321.51, 2333.02, 2303.26, 2322.23, 2316.43,
       2311.13, 2293.85, 2375.74, 2354.75, 2327.09, 2348.47, 2327.36,
       2345.01, 2338.59, 2360.67, 2353.24, 2334.2 , 2334.61, 2383.23,
       2422.84, 2427.81, 2413.94, 2380.32, 2386.97, 2358.73, 2339.65,
       2360.48, 2346.1 , 2310.43, 2316.67, 2327.59, 2302.57, 2304.87,
       2322.67, 2296.55, 2334.46, 2337.94, 2330.8 , 2316.27, 2323.65,
       2334.01, 2390.86, 2380.14, 2367.91, 2382.59, 2381.97, 2344.53,
       2376.89, 2335.6 , 2354.86, 2338.94, 2329.93, 2289.02, 2297.61,
       2279.8 , 2249.08, 2232.75, 2190.72, 2179.72, 2173.1 , 2165.64,
       2181.81, 2204

In [91]:
x_norm = (x - np.min(x)) / (np.max(x) - np.min(x))  # Normalización de x entre 0 y 1
y_norm = (y - np.min(y)) / (np.max(y) - np.min(y))
display(x_norm,y_norm)

array([9.00523374e-01, 8.99419660e-01, 9.24306619e-01, 9.68063517e-01,
       9.73320991e-01, 9.73392198e-01, 9.30501656e-01, 8.96535764e-01,
       9.02042463e-01, 8.76241678e-01, 9.17482584e-01, 9.29041906e-01,
       9.13839143e-01, 9.18467618e-01, 9.68027913e-01, 9.91443254e-01,
       1.00000000e+00, 9.45668815e-01, 9.31237465e-01, 9.37230747e-01,
       8.86459928e-01, 8.77535277e-01, 8.73547667e-01, 9.08130689e-01,
       8.67364498e-01, 8.70343338e-01, 8.36235032e-01, 8.38489930e-01,
       8.30384163e-01, 7.97783079e-01, 8.24022976e-01, 8.36804690e-01,
       8.23334639e-01, 8.71601334e-01, 8.35012639e-01, 8.33944529e-01,
       8.24189127e-01, 8.37849064e-01, 8.02530233e-01, 8.25043614e-01,
       8.18160240e-01, 8.11870260e-01, 7.91362552e-01, 8.88548676e-01,
       8.63637982e-01, 8.30811407e-01, 8.56184949e-01, 8.31131840e-01,
       8.52078660e-01, 8.44459477e-01, 8.70663771e-01, 8.61845931e-01,
       8.39249475e-01, 8.39736058e-01, 8.97437723e-01, 9.44446422e-01,
      

array([4.42624702e-01, 9.00523374e-01, 8.99419660e-01, 9.24306619e-01,
       9.68063517e-01, 9.73320991e-01, 9.73392198e-01, 9.30501656e-01,
       8.96535764e-01, 9.02042463e-01, 8.76241678e-01, 9.17482584e-01,
       9.29041906e-01, 9.13839143e-01, 9.18467618e-01, 9.68027913e-01,
       9.91443254e-01, 1.00000000e+00, 9.45668815e-01, 9.31237465e-01,
       9.37230747e-01, 8.86459928e-01, 8.77535277e-01, 8.73547667e-01,
       9.08130689e-01, 8.67364498e-01, 8.70343338e-01, 8.36235032e-01,
       8.38489930e-01, 8.30384163e-01, 7.97783079e-01, 8.24022976e-01,
       8.36804690e-01, 8.23334639e-01, 8.71601334e-01, 8.35012639e-01,
       8.33944529e-01, 8.24189127e-01, 8.37849064e-01, 8.02530233e-01,
       8.25043614e-01, 8.18160240e-01, 8.11870260e-01, 7.91362552e-01,
       8.88548676e-01, 8.63637982e-01, 8.30811407e-01, 8.56184949e-01,
       8.31131840e-01, 8.52078660e-01, 8.44459477e-01, 8.70663771e-01,
       8.61845931e-01, 8.39249475e-01, 8.39736058e-01, 8.97437723e-01,
      

## Compute cost

In [86]:
def compute_cost(x,y,w,b):
    m=x.shape[0] #Toma la cantidad de filas del vector de x (cantidad de features)
    cost =0

    for i in range(m):
        f_wb=w*x[i]+b 
        cost=cost+(f_wb-y[i])**2 #total error
        total_cost=1/(2*m)*cost #Average error
    return total_cost


## Compute gradient

In [87]:
def compute_gradient(x,y,w,b):
    m=x.shape[0]
    dj_dw=0
    dj_db=0

    for i in range(m):
        f_wb=w*x[i]+b #model 
        dj_dw_i=(f_wb-y[i])*x[i] #partial derivative of J(w,b) respect to w
        dj_db_i=f_wb-y[i] #partial derivative of J(w,b) respect to b
          #sum of dj_w for each feature
        dj_db+=dj_db_i
        dj_dw+=dj_dw_i  #sum of dj_b for each feature
    dj_dw=dj_dw/m  #1/m term multiplpy by dj_dw
    dj_db=dj_db/m   #1/m term multiplpy by dj_db

    return dj_dw,dj_db

## Gradient descent algorithm

In [88]:
def gradient_descent(x, y, w_in, b_in, alpha, num_iters, cost_function, gradient_function):

    J_history=[]
    p_history=[]
    b=b_in
    w=w_in

    for i in range(num_iters):
        dj_dw, dj_db =gradient_function(x, y, w, b)

        b=b-alpha *dj_db
        w=w-alpha*dj_dw

        if i<100000:
            J_history.append(cost_function(x, y, w, b))
            p_history.append([w, b])
        if i% math.ceil(num_iters/10)==0:
            print(f"Iteration {i:4}: Cost {J_history[-1]:0.2e}",
                  f"dj_dw: {dj_dw:0.3e}, dj_db: {dj_db:0.3e}",
                  f"w: {w:0.3e}, b:{b:0.5e}")
    return w, b, J_history, p_history 


In [90]:
w_init=0
b_init=0

iterations = 10000
tmp_alpha=0.001

w_final, b_final, J_hist, p_hist =gradient_descent(x_norm, y_norm, w_init, b_init, tmp_alpha,
                                                   iterations, compute_cost, compute_gradient)
print(f"(w,b) found by gradient descent: ({w_final:8.4f},{b_final:8.4f})")

Iteration    0: Cost 1.04e-01 dj_dw: -2.070e-01, dj_db: -3.930e-01 w: 2.070e-04, b:3.93050e-04
Iteration 1000: Cost 2.61e-02 dj_dw: -8.962e-02, dj_db: -1.127e-01 w: 1.375e-01, b:2.26503e-01
Iteration 2000: Cost 1.72e-02 dj_dw: -5.179e-02, dj_db: -2.547e-02 w: 2.047e-01, b:2.87220e-01
Iteration 3000: Cost 1.50e-02 dj_dw: -3.890e-02, dj_db: 1.374e-03 w: 2.490e-01, b:2.96653e-01
Iteration 4000: Cost 1.37e-02 dj_dw: -3.385e-02, dj_db: 9.354e-03 w: 2.850e-01, b:2.90472e-01
Iteration 5000: Cost 1.25e-02 dj_dw: -3.131e-02, dj_db: 1.145e-02 w: 3.175e-01, b:2.79815e-01
Iteration 6000: Cost 1.15e-02 dj_dw: -2.959e-02, dj_db: 1.173e-02 w: 3.479e-01, b:2.68148e-01
Iteration 7000: Cost 1.05e-02 dj_dw: -2.817e-02, dj_db: 1.145e-02 w: 3.768e-01, b:2.56536e-01
Iteration 8000: Cost 9.61e-03 dj_dw: -2.688e-02, dj_db: 1.102e-02 w: 4.043e-01, b:2.45298e-01
Iteration 9000: Cost 8.80e-03 dj_dw: -2.567e-02, dj_db: 1.055e-02 w: 4.306e-01, b:2.34515e-01
(w,b) found by gradient descent: (  0.4556,  0.2242)
